create table my_entity_one (id bigint generated by default as identity, version bigint not null, age integer, name varchar(255) not null, active boolean, two_id bigint, primary key (id));
create table my_entity_three (id bigint generated by default as identity, version bigint not null, name varchar(255) not null, publish_date timestamp, notes varchar(255), primary key (id));
create table my_entity_two (id bigint generated by default as identity, version bigint not null, title varchar(255) not null, three_id bigint, notes varchar(255), primary key (id));
alter table my_entity_one add constraint UK_bjsa36wc85eae493b89ceu06w unique (name);
alter table my_entity_three add constraint UK_4wwa8ddcckt4f7fy7x26krorg unique (name);
alter table my_entity_two add constraint UK_cb3a887bbhmag3vqcylj5nfcv unique (title);
alter table my_entity_one add constraint FK4auedjbwsj1emvrsntq2wpegv foreign key (two_id) references my_entity_two;
alter table my_entity_two add constraint FK2jpeagn0tiypypyb6q6cv9rpb foreign key (three_id) references my_entity_three;
